pipeline:
  name: harness-pipelines-parall
  identifier: harnesspipelinesparall
  projectIdentifier: palak_labs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: parallelism
        identifier: parallelism
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Starting deployment"
                          echo "Environment: <+matrix.env>"
                          echo "Replica count: <+matrix.replicas>"

                          if [ "<+matrix.env>" = "dev" ]; then
                            echo "This is DEV deployment"
                          elif [ "<+matrix.env>" = "test" ]; then
                            echo "This is TEST deployment"
                          else
                            echo "This is PROD deployment"
                          fi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  strategy:
                    matrix:
                      env:
                        - dev
                        - test
                        - prod
                      replicas:
                        - 1
                        - 2
                        - 3
                      exclude:
                        - env: prod
                          replicas: 1
                        - env: dev
                          replicas: 1,2
        tags: {}
